version: '3'
networks:
  default:
    external:
      name: prog_net
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    image: prog_image_application
    volumes:
      - .:/prog_image
    ports:
      - '3001:3001' 
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_NAME=prog_image_development